# -*- coding: utf-8 -*-
"""crewai-first-agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AwFp0z19V9GyLTfk4K6yPN8qBuzzv8cF
"""

!pip install nest_asyncio

from google.colab import userdata
import os
os.environ['GOOGLE_API_KEY'] = userdata.get('gemini')

print("done")

import os
from crewai import Agent, LLM, Task  # Importing the LLM class from CrewAI

# 1. Configure the Gemini model
gemini_llm = LLM(
    model="gemini/gemini-2.5-flash",
    temperature=0.5,
    api_key=os.environ["GOOGLE_API_KEY"]  # Uses the API key stored previously
)

# 2. Create the Agent and assign the new model to it
researcher_agent = Agent(
    role="Professional Market Researcher and Data Analyst",
    goal="Analyze data and gather the most accurate information and latest trends in any requested field",
    backstory="You are a professional researcher with 10 years of experience in generating reports and understanding markets with high accuracy.",
    llm=gemini_llm,  # Now Pydantic will accept it because it's the expected class type
    verbose=True
)

from crewai import Task

# Define the task and assign it to the Agent
research_task = Task(
    description="Analyze the importance of using AI Agents in the job market by 2026 and mention their most important advantage.",
    expected_output="A short report in English containing an introduction, key points, and a conclusion.",
    agent=researcher_agent  # Assigning the responsible agent for this task
)

print("Task has been successfully created and assigned to the Agent!")

import nest_asyncio

# This line automatically fixes the conflict between Google Colab and CrewAI
nest_asyncio.apply()

print("Environment has been configured successfully to fix the Event Loop issue!")

from crewai import Crew, Process

# 1. تجميع الموظفين والمهام
analysis_crew = Crew(
    agents=[researcher_agent],
    tasks=[research_task],
    process=Process.sequential
)


result = await analysis_crew.kickoff_async()


print("\n###################################")
print("## النتيجة المستلمة من الـ Agent:")
print("###################################\n")
print(result)